'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowUpRight, Check, Clock3, Heart, MessageCircle, QrCode, Sparkles, Store, Users } from 'lucide-react'
import { CTA, FeatureGrid, PageHero } from './site-shell'

type Kind = 'product' | 'how' | 'businesses' | 'about'
const content: Record<Kind, { eyebrow: string; title: string; body: string; image: string; imageAlt: string; accent: string; items: {title:string;body:string}[] }> = {
  product: { eyebrow: 'The product', title: 'A quieter way to stay close.', body: 'Regulars turns the moment after a great visit into a relationship that keeps growing.', image:'/images/regulars-cafe.png', imageAlt:'Barista serving coffee at an independent cafe', accent:'bg-primary', items:[{title:'Your voice, remembered',body:'Write messages that sound like the person behind the counter.'},{title:'Useful by default',body:'Send reminders and invitations that earn attention instead of interrupting it.'},{title:'A living list',body:'See who is with you, what they love, and when they might return.'}] },
  how: { eyebrow: 'How it works', title: 'From one good visit to a habit.', body: 'A simple three-part rhythm that fits into the way your team already works.', image:'/images/regulars-shop.png', imageAlt:'Warm neighborhood shop interior', accent:'bg-secondary', items:[{title:'Invite',body:'A QR code gives every happy customer a gentle way to stay connected.'},{title:'Remember',body:'Regulars keeps the context that makes a message feel human.'},{title:'Return',body:'The right nudge at the right time makes the next visit feel natural.'}] },
  businesses: { eyebrow: 'For independent places', title: 'Growth that feels like care.', body: 'Made for the restaurants, salons, studios, and shops that give a neighbourhood its character.', image:'/images/regulars-salon.png', imageAlt:'Stylist working in an independent salon', accent:'bg-accent', items:[{title:'Restaurants & cafés',body:'Bring back the table, dish, and people your guests talk about.'},{title:'Salons & studios',body:'Keep appointments warm and your quiet spots filled.'},{title:'Local shops',body:'Give regular customers a reason to choose you again.'}] },
  about: { eyebrow: 'About Regulars', title: 'Technology with good manners.', body: 'We build small, considerate tools for the people who make places worth returning to.', image:'/images/regulars-team.png', imageAlt:'Regulars team collaborating in a studio', accent:'bg-muted', items:[{title:'Thoughtful by design',body:'Every interaction should respect attention and feel worth opening.'},{title:'Independent at heart',body:'We build for real operators, not abstract growth charts.'},{title:'Made to last',body:'Simple systems create the strongest habits.'}] },
}

function Art({ kind }: { kind: Kind }) { const c=content[kind]; return <div className={`group relative min-h-[470px] overflow-hidden rounded-[2rem] ${c.accent}`}><Image src={c.image} alt={c.imageAlt} fill className="object-cover mix-blend-multiply opacity-85 transition-transform duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 50vw" /><div className="absolute inset-0 bg-gradient-to-t from-foreground/70 via-transparent to-transparent" /><div className="absolute bottom-7 left-7 right-7 flex items-end justify-between text-background"><div><p className="text-xs uppercase tracking-[.2em] opacity-75">Regulars field notes</p><p className="mt-2 font-serif text-3xl">Small moments add up.</p></div><span className="rounded-full bg-background/90 p-3 text-foreground"><Sparkles /></span></div></div> }

export function FeaturePage({ kind }: { kind: Kind }) { const c=content[kind]; return <><PageHero eyebrow={c.eyebrow} title={c.title} body={c.body} /><main className="mx-auto grid max-w-7xl gap-10 px-5 pb-20 md:grid-cols-[.9fr_1.1fr] md:px-8"><Art kind={kind} /><div className="flex flex-col justify-center"><div className="mb-8 flex items-center gap-3 text-sm text-muted-foreground"><Sparkles className="size-4 text-primary" /> A more human growth loop</div><FeatureGrid items={c.items} /></div></main>{kind==='how' && <section className="mx-auto max-w-7xl px-5 pb-20 md:px-8"><div className="grid overflow-hidden rounded-[2rem] border border-border bg-foreground text-background md:grid-cols-3">{[['01',QrCode,'Scan','A simple hello at the counter.'],['02',MessageCircle,'Connect','A direct line that feels personal.'],['03',Heart,'Come back','The next visit feels familiar.']].map(([n,I,label,body])=>{const Icon=I as typeof Check; return <div key={String(n)} className="border-background/15 p-8 md:border-r"><span className="font-mono text-primary">{n}</span><Icon className="my-12 text-primary" /><h3 className="font-serif text-3xl">{String(label)}</h3><p className="mt-3 text-sm leading-6 text-background/60">{String(body)}</p></div>})}</div></section>}{kind==='businesses' && <section className="mx-auto grid max-w-7xl gap-5 px-5 pb-20 md:grid-cols-3 md:px-8"><div className="md:col-span-2 rounded-[2rem] bg-foreground p-8 text-background md:p-12"><Users className="text-primary" /><p className="mt-16 max-w-xl font-serif text-4xl md:text-5xl">Built around the people who already love your place.</p><p className="mt-5 max-w-xl text-background/65">No discount treadmill. No noisy campaigns. Just a direct line to your community.</p></div><div className="rounded-[2rem] bg-primary p-8 text-primary-foreground"><Store /><p className="mt-28 font-serif text-3xl">Your regulars are already here.</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold">Meet them <ArrowUpRight /></Link></div></section>}{kind==='about' && <section className="mx-auto max-w-7xl px-5 pb-20 md:px-8"><div className="grid gap-5 md:grid-cols-[1.2fr_.8fr]"><div className="rounded-[2rem] bg-secondary p-8 md:p-12"><Heart className="text-primary"/><p className="mt-20 max-w-2xl font-serif text-4xl md:text-6xl">Good software should feel a little like good hospitality.</p></div><div className="rounded-[2rem] border border-border p-8"><Clock3 className="text-primary"/><p className="mt-20 text-lg leading-8 text-muted-foreground">We care about the details that make an experience feel considered: the right timing, the right tone, and no unnecessary noise.</p></div></div></section>}<CTA /></> }

export function ContactPage(){return <><PageHero eyebrow="Book a demo" title="Let’s make the next visit easy." body="Tell us a little about your place. We’ll show you how Regulars could fit into the rhythm you already have."/><section className="mx-auto grid max-w-7xl gap-8 px-5 pb-24 md:grid-cols-[1fr_.8fr] md:px-8"><form className="flex flex-col gap-5 rounded-[2rem] border border-border bg-secondary/40 p-7 md:p-10" onSubmit={e=>{e.preventDefault(); e.currentTarget.innerHTML='<div class="flex min-h-72 flex-col justify-center"><div class="mb-5 flex size-12 items-center justify-center rounded-full bg-primary text-primary-foreground"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="m5 12 4 4L19 6"/></svg></div><h2 class="font-serif text-4xl">You’re on the list.</h2><p class="mt-3 text-muted-foreground">We’ll be in touch soon.</p></div>'}}><label className="text-sm">Your name<input required className="mt-2 w-full rounded-xl border border-border bg-background p-3" /></label><label className="text-sm">Email address<input required type="email" className="mt-2 w-full rounded-xl border border-border bg-background p-3" /></label><label className="text-sm">What kind of place?<input required className="mt-2 w-full rounded-xl border border-border bg-background p-3" /></label><button className="mt-3 inline-flex items-center justify-center gap-2 rounded-full bg-primary px-5 py-3 font-medium text-primary-foreground">Show me Regulars <ArrowUpRight className="size-4" /></button></form><div className="relative min-h-[420px] overflow-hidden rounded-[2rem] bg-secondary"><Image src="/images/regulars-shop.png" alt="Independent local shop" fill className="object-cover opacity-75 mix-blend-multiply" sizes="(max-width: 768px) 100vw, 40vw"/><div className="absolute inset-0 bg-gradient-to-t from-foreground/75 to-transparent"/><div className="absolute bottom-8 left-8 right-8 text-background"><Clock3 className="text-primary"/><h2 className="mt-6 font-serif text-4xl">No pressure.<br/>Just a conversation.</h2><p className="mt-4 leading-7 text-background/70">We’ll bring examples, listen to how your business works, and leave the hard sell at home.</p></div></div></section></>}

export function LegalPage({kind}:{kind:'privacy'|'terms'}){return <><PageHero eyebrow={kind==='privacy'?'Privacy':'Terms'} title={kind==='privacy'?'Your information, treated with care.':'The simple version.'} body={kind==='privacy'?'We only collect what helps us provide Regulars and communicate with you.':'These terms explain the basics of using Regulars and our website.'}/><article className="mx-auto max-w-3xl px-5 pb-24 md:px-8"><div className="rounded-[2rem] bg-secondary/50 p-8 md:p-12"><h2 className="font-serif text-3xl">{kind==='privacy'?'What we collect':'Using the service'}</h2><p className="mt-5 leading-8 text-muted-foreground">We keep things clear, limited, and purposeful. If you have a question about this page, contact us and we’ll answer plainly.</p><h2 className="mt-12 font-serif text-3xl">Contact</h2><p className="mt-5 leading-8 text-muted-foreground">Reach out through the demo page and our team will help.</p></div></article></>}
