'use client'

import Link from 'next/link'
import { ArrowUpRight, Check, CircleDot, Clock3, Heart, MessageCircle, QrCode, Scissors, Sparkles, Store, Users, WandSparkles } from 'lucide-react'
import { CTA, FeatureGrid, PageHero } from './site-shell'

type Kind = 'product' | 'how' | 'businesses' | 'about'
const content: Record<Kind, { eyebrow: string; title: string; body: string; accent: string; items: {title:string;body:string}[] }> = {
  product: { eyebrow: 'The product', title: 'A quieter way to stay close.', body: 'Regulars turns the moment after a great visit into a relationship that keeps growing.', accent: 'bg-primary', items: [{title:'Your voice, remembered',body:'Write messages that sound like the person behind the counter.'},{title:'Useful by default',body:'Send reminders and invitations that earn attention instead of interrupting it.'},{title:'A living list',body:'See who is with you, what they love, and when they might return.'}] },
  how: { eyebrow: 'How it works', title: 'From one good visit to a habit.', body: 'A simple three-part rhythm that fits into the way your team already works.', accent: 'bg-secondary', items: [{title:'Invite',body:'A QR code gives every happy customer a gentle way to stay connected.'},{title:'Remember',body:'Regulars keeps the context that makes a message feel human.'},{title:'Return',body:'The right nudge at the right time makes the next visit feel natural.'}] },
  businesses: { eyebrow: 'For independent places', title: 'Growth that feels like care.', body: 'Made for the restaurants, salons, studios, and shops that give a neighbourhood its character.', accent: 'bg-accent', items: [{title:'Restaurants & cafés',body:'Bring back the table, dish, and people your guests talk about.'},{title:'Salons & studios',body:'Keep appointments warm and your quiet spots filled.'},{title:'Local shops',body:'Give regular customers a reason to choose you again.'}] },
  about: { eyebrow: 'About Regulars', title: 'Technology with good manners.', body: 'We build small, considerate tools for the people who make places worth returning to.', accent: 'bg-muted', items: [{title:'Thoughtful by design',body:'Every interaction should respect attention and feel worth opening.'},{title:'Independent at heart',body:'We build for real operators, not abstract growth charts.'},{title:'Made to last',body:'Simple systems create the strongest habits.'}] },
}

function Art({ kind }: { kind: Kind }) {
  const icons = { product: MessageCircle, how: QrCode, businesses: Store, about: Heart }
  const Icon = icons[kind]
  return <div className={`relative min-h-[360px] overflow-hidden rounded-[2rem] p-8 ${content[kind].accent}`}><div className="absolute -right-12 -top-12 size-56 rounded-full border-[28px] border-background/30" /><div className="absolute bottom-8 left-8 right-8 rounded-2xl bg-background p-6 shadow-xl"><div className="flex items-center justify-between"><span className="font-serif text-2xl">regulars<span className="text-primary">.</span></span><Icon className="text-primary" /></div><div className="mt-10 flex items-end gap-2"><span className="h-16 w-8 rounded-t-full bg-primary/70" /><span className="h-24 w-8 rounded-t-full bg-foreground/80" /><span className="h-12 w-8 rounded-t-full bg-primary/40" /><span className="ml-3 text-sm text-muted-foreground">small moments<br/>add up.</span></div></div></div>
}

export function FeaturePage({ kind }: { kind: Kind }) { const c = content[kind]; return <><PageHero eyebrow={c.eyebrow} title={c.title} body={c.body} /><main className="mx-auto grid max-w-7xl gap-10 px-5 pb-20 md:grid-cols-[.85fr_1.15fr] md:px-8"><Art kind={kind} /><div className="flex flex-col justify-center"><div className="mb-8 flex items-center gap-3 text-sm text-muted-foreground"><Sparkles className="size-4 text-primary" /> A more human growth loop</div><FeatureGrid items={c.items} /></div></main>{kind === 'how' && <section className="mx-auto flex max-w-7xl flex-col gap-5 px-5 pb-20 md:flex-row md:px-8">{[['01',QrCode,'Scan'],['02',MessageCircle,'Connect'],['03',Heart,'Come back']].map(([n,I,label]) => { const Icon=I as typeof Check; return <div key={String(n)} className="flex-1 rounded-3xl border border-border p-7"><span className="font-mono text-primary">{n}</span><Icon className="my-12 text-primary" /><h3 className="font-serif text-3xl">{String(label)}</h3></div>})}</section>}{kind === 'businesses' && <section className="mx-auto max-w-7xl px-5 pb-20 md:px-8"><div className="rounded-3xl bg-foreground p-8 text-background md:p-12"><div className="flex flex-wrap gap-8"><Users /><div><p className="font-serif text-3xl">Built around the people who already love your place.</p><p className="mt-3 max-w-xl text-background/70">No discount treadmill. No noisy campaigns. Just a direct line to your community.</p></div></div></div></section>}<CTA /></> }

export function ContactPage() { return <><PageHero eyebrow="Book a demo" title="Let’s make the next visit easy." body="Tell us a little about your place. We’ll show you how Regulars could fit into the rhythm you already have." /><section className="mx-auto grid max-w-7xl gap-10 px-5 pb-24 md:grid-cols-[1fr_.8fr] md:px-8"><form className="flex flex-col gap-5 rounded-3xl border border-border bg-secondary/30 p-7 md:p-10" onSubmit={(e)=>{e.preventDefault(); const el=e.currentTarget; el.innerHTML='<div class="flex min-h-72 flex-col justify-center"><div class="mb-5 flex size-12 items-center justify-center rounded-full bg-primary text-primary-foreground"><Check /></div><h2 class="font-serif text-4xl">You’re on the list.</h2><p class="mt-3 text-muted-foreground">We’ll be in touch soon.</p></div>'}}><label className="text-sm">Your name<input required className="mt-2 w-full rounded-xl border border-border bg-background p-3" /></label><label className="text-sm">Email address<input required type="email" className="mt-2 w-full rounded-xl border border-border bg-background p-3" /></label><label className="text-sm">What kind of place?<input required className="mt-2 w-full rounded-xl border border-border bg-background p-3" /></label><button className="mt-3 inline-flex items-center justify-center gap-2 rounded-full bg-primary px-5 py-3 font-medium text-primary-foreground">Show me Regulars <ArrowUpRight className="size-4" /></button></form><div className="flex flex-col justify-center rounded-3xl bg-secondary p-8"><Clock3 className="text-primary" /><h2 className="mt-8 font-serif text-4xl">No pressure.<br/>Just a conversation.</h2><p className="mt-5 leading-7 text-muted-foreground">We’ll bring a few examples, listen to how your business works, and leave the hard sell at home.</p></div></section></> }

export function LegalPage({ kind }: { kind: 'privacy' | 'terms' }) { return <><PageHero eyebrow={kind === 'privacy' ? 'Privacy' : 'Terms'} title={kind === 'privacy' ? 'Your information, treated with care.' : 'The simple version.'} body={kind === 'privacy' ? 'We only collect what helps us provide Regulars and communicate with you. We do not sell personal information.' : 'These terms explain the basics of using Regulars and our website.'} /><article className="prose prose-neutral mx-auto max-w-3xl px-5 pb-24 leading-8 text-muted-foreground md:px-8"><h2>{kind === 'privacy' ? 'What we collect' : 'Using the service'}</h2><p>We keep things clear, limited, and purposeful. If you have a question about this page, contact us and we’ll answer plainly.</p><h2>Contact</h2><p>Reach out through the demo page and our team will help.</p></article></> }
